# general
seed: 42
dataset_dir: "./datasets"

# train options
batch_size: 512
start_epoch: 0
epochs: 100
dataset:  "PROTEINS" # Options are: "ogbg-molhiv", "ogbg-ppa", "TWITTER-Real-Graph-Partial", "Yeast", "PROTEINS", "DD", "reddit_threads", "twitch_egos", "REDDIT-BINARY", "TRIANGLES", "MNISTSuperpixels"
device: "cpu" # Options are: "cpu", "cuda"
used_loss: "default" # Options are: "instanceonly", "clusteronly", "default"
checkpoint_interval: 10

#augmentation settings for contrastive learning
augmode: "default" # Options are: "default", "subgraphonly", "masknodesonly", "permuteedgesonly", "dropnodesonly", "noaug"
drop_nodes_ratio: 0.2
subgraph_ratio: 0.8
permute_edges_ratio: 0.2
mask_nodes_ratio: 0.2

# model options
feature_dim: 64
model_path: "save/modelname"
reload: False
n_clusters: -1 # Options are -1 for inferring n_clusters from a given labeled dataset or a positive integer

# loss options
learning_rate: 0.001
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0

# inference
inference_epoch: 100
inference_save_path: "results"


