# general
seed: 42
workers: 8
dataset_dir: "./datasets"
augmentation_workers: 10

# train options
batch_size: 512
image_size: 224
start_epoch: 0
epochs: 500
dataset:  "constructedgraphs_4" #"CeiloGraphs" #constructedgraphs_2size / TwitchVsGithub_balanced / TwitchVsDeezerEgos_balanced / Yeast / twitch_egos / constructedgraphs_2nodedeg / constructedgraphs_2 / ogbg-molhiv / CeiloGraphs # MNISTSuperpixels / reddit_threads / COLLAB / TWITTER-Real-Graph-Partial / DBLP_v1 / MCF-7 / PROTEINS / REDDIT-BINARY / NCI1 / CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet
device: "cpu" #"cpu" / "cuda"
augmode: "default"#"subgraphonly"#"masknodesonly"#"permuteedgesonly"#"dropnodesonly"#"noaug"
used_loss: "default"#"instanceonly"#"clusteronly"#"default"
gnn_model: "default"#"gcnsimplepool"#default

# model options
resnet: "ResNet34" # ResNet18 / ResNet34 / ResNet50
feature_dim: 64
model_path: "save/ceilographs16"
reload: False

# loss options
learning_rate: 0.001 # ->0.001<- standard
weight_decay: 0.
instance_temperature: 0.5 #0.5
cluster_temperature: 1.0 #1.0

# ceilo options
graphpicklepath: "/home/rigel/MDammann/PycharmProjects/CC4Graphs/ceilo_graph_generation/graphs_processed.pickle"
ceilo_n_clusters: 8
